/**
 * THE APEX — every number the object is built from, in one place.
 *
 * The object is a machined, hollow, matte-black pyramid with a gold-lit
 * mechanism suspended inside it. It is the brand's one physical claim: the
 * housing is deliberately plain, and the only warm light in the scene is
 * generated by a working part deep inside it. Value is in the system, not on
 * its surface.
 *
 * Colour is not restated here. Every value is read from the semantic token
 * tier (Ch.13 / ADR-0003: tokens are defined exactly once, as data), and the
 * 3D layer consumes the typed TS output rather than the CSS custom properties
 * because a WebGL material needs a parsed colour, not a `var()` reference.
 *
 * The palette is enforced by omission: black, graphite, titanium, gold. There
 * is no fifth colour anywhere in this directory.
 */

import { semanticTokens } from "@trady-perch/tokens";

/**
 * Materials, by role. `key` and `fill` are lights rather than surfaces, but
 * they are colours drawn from the same four-value palette and belong with it.
 */
export const PALETTE = {
  /** The housing. Anodised black — the plainest thing in the frame. */
  anodised: semanticTokens.color.background.secondary,
  /** Machined interior surfaces, one step up from the housing. */
  graphite: semanticTokens.color.surface.cardHover,
  /** The mechanism. Bare machined titanium. */
  titanium: semanticTokens.color.text.tertiary,
  /** Highlights on the mechanism, where a facet catches the key. */
  titaniumLit: semanticTokens.color.text.secondary,
  /** The working part. Real metallic gold, never neon. */
  gold: semanticTokens.color.accent.primary,
  /** The heart of the emitter, where the gold reads as light rather than metal. */
  goldHot: semanticTokens.color.accent.secondary,
  /** The key light. Warm off-white, not white — a tungsten studio head. */
  key: semanticTokens.color.text.primary,
  /**
   * The fill and rim. Cool, and eight stops down from the key: shadow is
   * retained, never lifted. Graphite reads blue-cool against gold.
   */
  fill: semanticTokens.color.text.tertiary,
} as const;

/**
 * The shell. A square-based pyramid assembled from four machined face plates,
 * a solid apex fitting and a plinth — not a modelled solid. Proportion is the
 * whole game: at 1.84 tall on a 2.4 base the faces rise at 57°, steeper than
 * anything architectural and much steeper than anything Egyptian, which is
 * what keeps it reading as an instrument.
 *
 * Units are metres-ish; the camera is placed to suit.
 */
export const SHELL = {
  baseHalfWidth: 1.2,
  height: 1.84,
  /** Plate stock thickness, bevels included. */
  plateThickness: 0.055,
  /** The chamfer around every plate edge. Small enough to still read sharp. */
  plateBevel: 0.013,
  /**
   * How far the triangular aperture is inset from the plate outline, measured
   * perpendicular to each edge. This is the single number that decides whether
   * the object reads as a solid with holes in it (too large) or as a wireframe
   * (too small).
   */
  apertureMargin: 0.325,
  /**
   * The pose the object rests in: turned twenty-two degrees off square.
   *
   * Dead-on, a pyramid is a triangle — a flat sign of itself, with no way to
   * read that it has depth at all. Turned far enough to open a second face and
   * no further, it becomes an object. This is the standard three-quarter of
   * product photography and it is standard because nothing else works.
   */
  restYaw: 0.38,
  /** Fraction of the total height occupied by the solid apex fitting. */
  apexCapFraction: 0.15,
  /** The apex fitting stands very slightly proud, so the seam is visible. */
  apexCapProud: 1.035,
  /** Plinth: the machined collar the four plates land on. */
  plinthHeight: 0.072,
  plinthOverhang: 0.045,
  plinthInset: 0.14,
  /** Fastener heads, three per plate. */
  screwRadius: 0.026,
  screwHeight: 0.014,
} as const;

/**
 * The mechanism. Concentric machined rings on independent axes around a
 * gold emitter, with a bladed aperture in front of it. It is not a depiction
 * of anything — it is a precision assembly that happens to be the only light
 * source inside the housing.
 */
export const MECHANISM = {
  /**
   * The height at which all four apertures see it. Not the centre of the
   * pyramid — the centre of the *opening*, which sits lower, because the
   * aperture is inset from a triangle that narrows as it rises.
   */
  centreY: 0.63,
  /** Outermost gimbal. Everything else is proportional to this. */
  radius: 0.47,
  ringBand: 0.035,
  ringHeight: 0.055,
  ringChamfer: 0.008,
  ringSegments: 72,
  discSegments: 64,
  irisBlades: 8,
  bearingCount: 14,
  bearingRadius: 0.018,
  emitterRadius: 0.072,
} as const;

/**
 * Motion. Every rate here is chosen to sit at or just below the threshold of
 * perception — the object should never be caught animating. Nothing loops on a
 * visible period, nothing eases on a digital curve, and the only fast thing in
 * the scene is the iris detent, which is fast because a mechanism settling is
 * fast.
 */
export const RATES = {
  /** Shell yaw, rad/s. ~11 minutes per revolution. */
  shellYaw: 0.0094,
  /** The suspension: two incommensurate periods, so it never repeats visibly. */
  shellDrift: { amplitude: 0.016, slowHz: 0.041, fastHz: 0.067 },
  shellSway: { amplitude: 0.0075, slowHz: 0.031, fastHz: 0.053 },
  /** The mechanism turns inside the shell, independently. */
  mechanismYaw: 0.021,
  /** Gimbal rates, rad/s. Different speeds, different directions, no factor. */
  gimbal: [0.051, -0.033, 0.0187] as const,
  /** Turned discs, counter-rotating against the gimbals. */
  disc: [-0.026, 0.041] as const,
  /** Seconds between iris detents. Prime-ish, so it never syncs to anything. */
  irisIntervalSeconds: 6.7,
  /** Natural frequency of the iris detent. High: a mechanism settles hard. */
  irisOmega: 9.5,
  /**
   * Natural frequency of the key light's travel. Low: swinging a heavy lamp,
   * about 1.2s to settle. This single number is where the luxury lives — at
   * 3x this value the same scene reads as a cursor follower.
   */
  lightOmega: 3.05,
} as const;

/**
 * The rig. Luxury product photography, not a game camera: a long lens well
 * back, so the pyramid's parallel edges stay nearly parallel and the object
 * gains the depth compression that reads as "photographed" rather than
 * "rendered".
 *
 * fov is vertical, so 19° is the vertical angle of view of an 85mm lens on
 * full-frame (2·atan(12/85) = 16°, opened slightly to breathe).
 */
export const RIG = {
  fov: 19,
  /**
   * Eighteen units back on a 19° lens. Absurdly far for a scene this size, and
   * that is the point: at this distance the pyramid's converging edges stay
   * nearly parallel and the near and far faces sit almost on top of each
   * other. That flattening is what separates a photographed object from a
   * rendered one, and no amount of material work substitutes for it.
   */
  position: [0, 0.95, 15.2] as const,
  target: [0, 0, 0] as const,
  /** Bracketing the object tightly; the depth buffer has precision to spare. */
  near: 10,
  far: 23,
  /**
   * How far the object is dropped relative to the camera's aim, which is what
   * lifts it above the frame's centre line. Roughly a sixth of the frame
   * height — enough to feel composed, not enough to feel like a mistake.
   */
  objectOffsetY: -0.25,
  /** The plane the shadow and the pool of light live on. No floor is drawn. */
  groundY: -0.45,
  /** Distance of the key light from the object as it orbits. */
  keyDistance: 7.2,
  /** How far the key swings, in radians, at full pointer deflection. */
  keyAzimuthRange: 0.72,
  /**
   * Elevation band. Never below the horizon — this is a studio, not a stage.
   * The top of the band sits close to the faces' own normal elevation, which
   * is where a raking light finds the machining rather than skating over it.
   */
  keyElevation: { high: 0.88, low: 0.22 },
  /** Where the key rests when there is no pointer: upper left, as designed. */
  keyRest: { x: -0.42, y: -0.2 },
} as const;

/**
 * Ambient particulate: metallic filings suspended in the volume around the
 * object, not glitter. They barely move; what changes is whether their facet
 * happens to be turned toward the key.
 */
export const DUST = {
  desktopCount: 520,
  mobileCount: 190,
  innerRadius: 1.35,
  outerRadius: 3.6,
  /** Fraction of flecks that are gold rather than titanium. */
  goldFraction: 0.22,
  /** Pixel size at one unit from the camera, before per-fleck scaling. */
  size: 62,
} as const;

/** Deterministic seeds. The same surface every visit, so detail is learnable. */
export const SEEDS = {
  shellSurface: 0x5a17,
  markedSurface: 0x2f91,
  mechanismSurface: 0x71c3,
  dust: 0x1d4b,
} as const;
