// Design token build pipeline — Product Implementation Constitution Ch.13.
//
// Reads structured JSON (src/core.json, src/semantic.json) and generates:
//   dist/tokens.css — CSS custom properties (core, then semantic referencing core via var())
//   dist/tokens.ts  — typed, nested TypeScript constants with fully-resolved literal values
//
// This file is the only place token values are transformed. dist/ output is
// never hand-edited (Ch.13 §8) — it is regenerated by `npm run build`.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const srcDir = join(__dirname, "..", "src");
const distDir = join(__dirname, "..", "dist");

const core = JSON.parse(readFileSync(join(srcDir, "core.json"), "utf-8"));
const semantic = JSON.parse(readFileSync(join(srcDir, "semantic.json"), "utf-8"));

const camelToKebab = (segment) =>
  segment.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();

/** Recursively walks a token tree, skipping metadata keys (prefixed `_`). */
function walk(node, path, visit) {
  for (const [key, value] of Object.entries(node)) {
    if (key.startsWith("_")) continue;
    const nextPath = [...path, key];
    if (value !== null && typeof value === "object" && !("ref" in value) && !("value" in value)) {
      walk(value, nextPath, visit);
    } else {
      visit(nextPath, value);
    }
  }
}

// --- Flatten core (leaves are plain string values) ---
const coreEntries = []; // { path: string[], value: string }
walk(core, [], (path, value) => {
  if (typeof value === "string") coreEntries.push({ path, value });
});
const coreByDotPath = new Map(coreEntries.map((e) => [e.path.join("."), e]));

function resolveCoreRef(ref) {
  // ref strings look like "core.color.black.950" — strip the leading "core."
  const dotPath = ref.replace(/^core\./, "");
  const entry = coreByDotPath.get(dotPath);
  if (!entry) throw new Error(`Unresolvable token reference: ${ref}`);
  return entry;
}

// --- Flatten semantic (leaves are { ref } or { value }) ---
const semanticEntries = []; // { path: string[], cssValue: string, tsValue: string }
walk(semantic, [], (path, leaf) => {
  if (leaf && typeof leaf === "object" && "ref" in leaf) {
    const resolved = resolveCoreRef(leaf.ref);
    const cssVarName = `--core-${resolved.path.map(camelToKebab).join("-")}`;
    semanticEntries.push({ path, cssValue: `var(${cssVarName})`, tsValue: resolved.value });
  } else if (leaf && typeof leaf === "object" && "value" in leaf) {
    semanticEntries.push({ path, cssValue: leaf.value, tsValue: leaf.value });
  } else {
    throw new Error(`Semantic token at ${path.join(".")} must have a "ref" or "value" key`);
  }
});

// --- Emit CSS ---
const cssLines = [
  "/* GENERATED FILE — do not hand-edit. Source: packages/tokens/src/*.json */",
  ":root {",
  "  /* Core tier — Design System Bible Ch.3-11 */",
];
for (const { path, value } of coreEntries) {
  cssLines.push(`  --core-${path.map(camelToKebab).join("-")}: ${value};`);
}
cssLines.push("", "  /* Semantic tier — references core tokens by role */");
for (const { path, cssValue } of semanticEntries) {
  cssLines.push(`  --semantic-${path.map(camelToKebab).join("-")}: ${cssValue};`);
}
cssLines.push("}", "");

// --- Emit TS (nested, fully-resolved literal values) ---
function toNestedObject(entries, valueKey) {
  const root = {};
  for (const entry of entries) {
    const { path } = entry;
    const leafValue = entry[valueKey];
    let node = root;
    for (let i = 0; i < path.length - 1; i += 1) {
      node[path[i]] ??= {};
      node = node[path[i]];
    }
    node[path[path.length - 1]] = leafValue;
  }
  return root;
}

const coreTree = toNestedObject(coreEntries, "value");
const semanticTree = toNestedObject(semanticEntries, "tsValue");

const tsLines = [
  "// GENERATED FILE — do not hand-edit. Source: packages/tokens/src/*.json",
  "// Product Implementation Constitution Ch.13 — typed constants for values consumed in logic, not styles.",
  "",
  `export const coreTokens = ${JSON.stringify(coreTree, null, 2)} as const;`,
  "",
  `export const semanticTokens = ${JSON.stringify(semanticTree, null, 2)} as const;`,
  "",
];

mkdirSync(distDir, { recursive: true });
writeFileSync(join(distDir, "tokens.css"), cssLines.join("\n"), "utf-8");
writeFileSync(join(distDir, "tokens.ts"), tsLines.join("\n"), "utf-8");

console.log(
  `[tokens] built ${coreEntries.length} core + ${semanticEntries.length} semantic tokens -> dist/tokens.css, dist/tokens.ts`,
);
