import type { CaseStudy } from "../case-study-types";

/**
 * Case study: Modi Store.
 *
 * ── Why this one is short, on purpose ─────────────────────────────────────
 *
 * Modi Store is a single `index.html` and a logo. That is the whole
 * repository. It is a real, deployed, working storefront — and it is not a
 * fourteen-chapter engineering narrative, because there is no fourteen-chapter
 * engineering narrative to tell about it.
 *
 * So this study supplies a hero, a snapshot, an overview and a stack, and
 * omits everything else. The sections it omits render nothing at all: no
 * empty frames, no "coming soon", no invented Research & Strategy chapter
 * describing decisions nobody made.
 *
 * This is the case that proves the architecture. A system where every project
 * must fill every section is a system that manufactures padding, and padding
 * is exactly what a prospective client learns to discount. A short case study
 * that is entirely true is worth more than a long one that is mostly filler —
 * and because the page links to the source, the difference is one click away
 * from being obvious.
 *
 * If this project grows — a build step, a cart, a payment integration — the
 * study grows with it by adding keys to this object. Nothing else changes.
 */
export const MODI_STORE: CaseStudy = {
  slug: "modi-store",
  repoName: "MODI-STORE",

  hero: {
    category: "Commerce",
    title: "Modi Store",
    standfirst:
      "A deployed storefront written by hand — no theme, no page builder, no framework. One document, shipped and reachable.",
  },

  snapshot: {
    facts: [
      { label: "Platform", value: "Web storefront" },
      { label: "Industry", value: "Retail" },
      { label: "Team", value: "Solo build" },
      { label: "Approach", value: "Hand-written" },
      { label: "Deployment", value: "Vercel" },
    ],
  },

  overview: {
    heading: "Written, not assembled",
    body: [
      "Modi Store is a storefront built directly in HTML and CSS rather than assembled from a theme or generated by a page builder. The entire thing is one document, deployed and publicly reachable, which means the markup, the styling and the interaction can all be inspected exactly as they shipped.",
      "That is the interesting part, and it is the only claim this page makes about it. There is no build pipeline to describe, no architecture diagram, and no set of hard tradeoffs that had to be resolved — it is a small project, and a case study that pretended otherwise would be easy to disprove by opening the repository linked at the top of this page.",
      "The reason it is here at all is that it is real and it is live. A portfolio that only shows the impressive things is a portfolio that has been edited; this section shows what exists.",
    ],
  },

  stack: [
    { group: "Frontend", items: ["HTML", "CSS"] },
    { group: "Infrastructure", items: ["Vercel"] },
  ],

  cta: {
    heading: "Need something bigger than a single page?",
    body: "Most of what we build has rather more moving parts than this. Tell us what you have in mind and we will scope it honestly.",
  },

  seo: {
    title: "Modi Store — a hand-written storefront",
    description:
      "A deployed storefront built directly in HTML and CSS rather than assembled from a theme — inspectable exactly as it shipped.",
  },
};
